### ISSUE TITLE
Having problems compiling

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [redstrate/prism#1]
Thanks for making this render framework available -- it looks really good and I almost have it all compiled.

I did have some problems with compiling it for 64bit using Visual Studio 17 because there were quite a number of wrong defines in Win64 Debug -- like it having WIN32 and \MACHINE:X86 in the compile/linking parameters.

In any case I've gotten through all that and everything builds fine (INCLUDING THE LOG project!) except for ShaderCompilerTool which, as you can see can't compile the log.hpp despite the fact that the log project quite happily does.  I've gone through their project options a billion time and don't see what would make one compile and the other not.

Any insight you can give me would be greatly appreciated.

[code]#1) Shader Compiler Tool won't itself compile, much less a shader... :)
1>------ Build started: Project: glslang-build-info, Configuration: Debug x64 ------
2>------ Build started: Project: ShaderCompilerTool, Configuration: Debug x64 ------
2>main.cpp
C:\DEV\prism\engine\log\include\log.hpp(40): error C2665: 'console::internal_format': none of the 2 overloads could convert all the argument types
C:\DEV\prism\engine\log\include\log.hpp(29): note: could be 'void console::internal_format(std::string &,const char *&)'
C:\DEV\prism\engine\log\include\log.hpp(24): note: or       'void console::internal_format(std::string &,const std::string &)'
C:\DEV\prism\engine\log\include\log.hpp(37): note: while trying to match the argument list '(std::string, std::filesystem::path)'
C:\DEV\prism\engine\log\include\log.hpp(46): note: see reference to function template instantiation 'void console::internal_print<std::filesystem::path&,std::filesystem::path&>(const Level,const System,const std::string_view,std::filesystem::path &,std::filesystem::path &)' being compiled
C:\DEV\prism\tools\shadercompiler\main.cpp(36): note: see reference to function template instantiation 'void console::info<std::filesystem::path&,std::filesystem::path&>(const System,const std::string_view,std::filesystem::path &,std::filesystem::path &)' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\filesystem(2392): note: see reference to class template instantiation 'std::chrono::time_point<std::filesystem::_File_time_clock,std::filesystem::_File_time_clock::duration>' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(616): note: see reference to class template instantiation 'std::basic_string_view<wchar_t,std::char_traits<wchar_t>>' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2124): note: see reference to class template instantiation 'std::is_convertible<const _StringViewIsh &,std::basic_string_view<wchar_t,std::char_traits<wchar_t>>>' being compiled
2>        with
2>        [
2>            _StringViewIsh=const wchar_t *
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2122): note: see reference to variable template 'const bool conjunction_v<std::is_convertible<wchar_t const * const &,std::basic_string_view<wchar_t,std::char_traits<wchar_t> > >,std::negation<std::is_convertible<wchar_t const * const &,wchar_t const *> > >' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2281): note: see reference to alias template instantiation 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::_Is_string_view_ish<_StringViewIsh>' being compiled
2>        with
2>        [
2>            _StringViewIsh=const wchar_t *
2>        ]
2>Done building project "ShaderCompilerTool.vcxproj" -- FAILED.

========== Build: 1 succeeded, 1 failed, 15 up-to-date, 0 skipped ==========

#1) GFXVulkan is being very illogical by not compiling.

1>------ Build started: Project: glslang-build-info, Configuration: Debug x64 ------

2>------ Build started: Project: ShaderCompilerTool, Configuration: Debug x64 ------
2>main.cpp
C:\DEV\prism\engine\log\include\log.hpp(40): error C2665: 'console::internal_format': none of the 2 overloads could convert all the argument types
C:\DEV\prism\engine\log\include\log.hpp(29): note: could be 'void console::internal_format(std::string &,const char *&)'
C:\DEV\prism\engine\log\include\log.hpp(24): note: or       'void console::internal_format(std::string &,const std::string &)'
C:\DEV\prism\engine\log\include\log.hpp(37): note: while trying to match the argument list '(std::string, std::filesystem::path)'
C:\DEV\prism\engine\log\include\log.hpp(46): note: see reference to function template instantiation 'void console::internal_print<std::filesystem::path&,std::filesystem::path&>(const Level,const System,const std::string_view,std::filesystem::path &,std::filesystem::path &)' being compiled
C:\DEV\prism\tools\shadercompiler\main.cpp(36): note: see reference to function template instantiation 'void console::info<std::filesystem::path&,std::filesystem::path&>(const System,const std::string_view,std::filesystem::path &,std::filesystem::path &)' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\filesystem(2392): note: see reference to class template instantiation 'std::chrono::time_point<std::filesystem::_File_time_clock,std::filesystem::_File_time_clock::duration>' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\type_traits(616): note: see reference to class template instantiation 'std::basic_string_view<wchar_t,std::char_traits<wchar_t>>' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2124): note: see reference to class template instantiation 'std::is_convertible<const _StringViewIsh &,std::basic_string_view<wchar_t,std::char_traits<wchar_t>>>' being compiled
2>        with
2>        [
2>            _StringViewIsh=const wchar_t *
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2122): note: see reference to variable template 'const bool conjunction_v<std::is_convertible<wchar_t const * const &,std::basic_string_view<wchar_t,std::char_traits<wchar_t> > >,std::negation<std::is_convertible<wchar_t const * const &,wchar_t const *> > >' being compiled
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xstring(2281): note: see reference to alias template instantiation 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::_Is_string_view_ish<_StringViewIsh>' being compiled
2>        with
2>        [
2>            _StringViewIsh=const wchar_t *
2>        ]
2>Done building project "ShaderCompilerTool.vcxproj" -- FAILED.
3>------ Build started: Project: BuildShaders, Configuration: Debug x64 ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): warning MSB8017: A circular dependency has been detected while executing custom build commands for item DEV\prism\CMakeFiles\ee4f04dfefd25cd4d5a58ba3fcb9ac37\mesh.vert.nocompile.glsl.rule". This may cause incremental build to work incorrectly.
3>Building Custom Rule C:/dev/prism/engine/renderer/CMakeLists.txt
3>Generating ../../shaders/mesh.vert.nocompile.glsl
3>'DEV\prism\bin\Debug\ShaderCompilerTool.exe"' is not recognized as an internal or external command,
3>operable program or batch file.
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 9009.
3>Done building project "BuildShaders.vcxproj" -- FAILED.
4>------ Build started: Project: Renderer, Configuration: Debug x64 ------
4>renderer.cpp
[/code]

**Comment by redstrate** [comment]
Thanks for trying to compile my little toy project! :-) it should actually happily compile now under Visual Studio (I tested this very recently) but I only tried with the latest VS19 (or is it 20 now?) so that might be the issue.

**Comment by redstrate** [comment]
Another note, I'm not sure why WIN32 etc is being defined on your end - I'll be able take a look later tonight and see what's being put in my linker settings.

Also beware that if you do get it compiled the vulkan backend might be broken at the moment (on my machine I'm overloading some push constants), but I can take a look at making it work tonight as well.

**Comment by redstrate** [comment]
Okay so I pushed af3993a and 0664ec6 which means it'll compile successfully under MSVC now. Interestingly, I encountered the same errors you did so I guess my memory was faulty :-D

**Comment by redstrate** [comment]
I'm closing the issue now because I believe I've fixed the compilation problems. I'm working on getting Vulkan support back, but I think the original issue should be solved!
